### ISSUE TITLE
Incompatible with sound input and output device chooser

### ISSUE THREAD

**Issue by obra** [julio641742/extend-panel-menu#10]
https://extensions.gnome.org/extension/906/sound-output-device-chooser/  adds some features to the panel menu to let the user switch sound devices at runtime. It looks like however you're pulling apart the panel menu doesn't notice this, so I end up with only the basic volume slider

It'd be lovely to see this fixed if you're able.

Thanks!

**Comment by julio641742** [comment]
Thanks for the feedback, I'll look into it.

**Comment by obra** [comment]
Much appreciated. Thanks for the quick response and building the extension in the first place.
If it's useful to you, I'm happy to test a git branch or a proposed patch

**Comment by JasonLG1979** [comment]
Not trying to hijack this issue but this would apply to all extensions that add functionality to the aggregate menu. It might be a good idea to just hack up the actual agg menu and use it in place of the user indicator instead of re-implementing  many of the features found in the agg menu. You can hide sections in the agg menu as you move them out as separate indicators.

**Comment by julio641742** [comment]
Thanks for all your feedback, the feature that you wanted is now ready
